#pragma once

#include <windows.h>

extern "C" {
extern FARPROC orig_WinHttpOpen;
extern FARPROC orig_WinHttpConnect;
extern FARPROC orig_WinHttpSendRequest;
extern FARPROC orig_WinHttpCloseHandle;
extern FARPROC orig_WinHttpOpenRequest;
extern FARPROC orig_WinHttpReadData;
extern FARPROC orig_WinHttpQueryHeaders;
extern FARPROC orig_WinHttpAddRequestHeaders;
extern FARPROC orig_WinHttpQueryDataAvailable;
extern FARPROC orig_WinHttpReceiveResponse;
extern FARPROC orig_WinHttpAddRequestHeadersEx;
extern FARPROC orig_WinHttpCheckPlatform;
extern FARPROC orig_WinHttpCrackUrl;
extern FARPROC orig_WinHttpCreateProxyResolver;
extern FARPROC orig_WinHttpCreateUrl;
extern FARPROC orig_WinHttpDetectAutoProxyConfigUrl;
extern FARPROC orig_WinHttpFreeProxyResult;
extern FARPROC orig_WinHttpFreeProxySettingsEx;
extern FARPROC orig_WinHttpFreeQueryConnectionGroupResult;
extern FARPROC orig_WinHttpGetDefaultProxyConfiguration;
extern FARPROC orig_WinHTTPGetIEProxyConfigForCurrentUser;
extern FARPROC orig_WinHttpGetProxyForUrl;
extern FARPROC orig_WinHttpGetProxyForUrlEx;
extern FARPROC orig_WinHttpGetProxyResult;
extern FARPROC orig_WinHttpGetProxySettingsEx;
extern FARPROC orig_WinHttpGetProxySettingsResultEx;
extern FARPROC orig_WinHttpQueryAuthSchemes;
extern FARPROC orig_WinHttpQueryConnectionGroup;
extern FARPROC orig_WinHttpQueryHeadersEx;
extern FARPROC orig_WinHttpQueryOption;
extern FARPROC orig_WinHttpReadDataEx;
extern FARPROC orig_WinHttpRegisterProxyChangeNotification;
extern FARPROC orig_WinHttpResetAutoProxy;
extern FARPROC orig_WinHttpSetCredentials;
extern FARPROC orig_WinHttpSetDefaultProxyConfiguration;
extern FARPROC orig_WinHttpSetOption;
extern FARPROC orig_WinHttpSetStatusCallback;
extern FARPROC orig_WinHttpSetTimeouts;
extern FARPROC orig_WinHttpTimeFromSystemTime;
extern FARPROC orig_WinHttpTimeToSystemTime;
extern FARPROC orig_WinHttpUnregisterProxyChangeNotification;
extern FARPROC orig_WinHttpWriteData;
extern FARPROC orig_WinHttpWebSocketClose;
extern FARPROC orig_WinHttpWebSocketCompleteUpgrade;
extern FARPROC orig_WinHttpWebSocketQueryCloseStatus;
extern FARPROC orig_WinHttpWebSocketReceive;
extern FARPROC orig_WinHttpWebSocketSend;
extern FARPROC orig_WinHttpWebSocketShutdown;
}

bool proxy_init_winhttp();
