name: Build & Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchains
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 nsis

      - name: Build for production
        run: bash scripts/build.sh ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: jeode ${{ github.ref_name }}
          draft: true
          files: |
            build/jeode-installer.exe
            build/winhttp.dll
            build/jeode/libjeode.dll
